// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace Model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190124111528_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Models.Account", b =>
                {
                    b.Property<Guid>("IdAccount")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BillAddress");

                    b.Property<DateTime>("Closed");

                    b.Property<Guid>("CustomerId");

                    b.Property<bool>("IsClosed");

                    b.Property<DateTime>("Open");

                    b.HasKey("IdAccount");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new { IdAccount = new Guid("fd73649b-5411-4e0c-8d04-f10293bbee05"), BillAddress = "5 avenue new-york, usa", Closed = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), CustomerId = new Guid("9d6a4941-2133-4fae-a148-e4a52880ee18"), IsClosed = true, Open = new DateTime(2019, 1, 24, 0, 0, 0, 0, DateTimeKind.Local) },
                        new { IdAccount = new Guid("45e13b84-31ed-4920-922a-60f01841d311"), BillAddress = "5 avenue new-york, usa", Closed = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), CustomerId = new Guid("1fed12ee-bf69-4908-bd01-4a6b48fbf486"), IsClosed = true, Open = new DateTime(2019, 1, 24, 0, 0, 0, 0, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("Model.Models.Article", b =>
                {
                    b.Property<Guid>("IdArticle")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activate");

                    b.Property<int>("DelievryTime");

                    b.Property<string>("Description");

                    b.Property<string>("Label");

                    b.Property<int>("PriceHT");

                    b.Property<int>("Tax");

                    b.HasKey("IdArticle");

                    b.ToTable("Articles");

                    b.HasData(
                        new { IdArticle = new Guid("78ace119-29bc-4903-a68f-fa10db32bcbf"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "Creme hydradanteXXL", PriceHT = 12, Tax = 3 },
                        new { IdArticle = new Guid("78ace119-29bc-4903-a68f-fa10db32bcaa"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "Creme hydradanteXXL", PriceHT = 12, Tax = 3 },
                        new { IdArticle = new Guid("78ace119-29bc-4903-a68f-fa10db32bcbb"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "pomade tonic", PriceHT = 12, Tax = 3 },
                        new { IdArticle = new Guid("c170110d-1355-4060-9926-2028988d970c"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "Creme hydradanteXXL", PriceHT = 12, Tax = 3 }
                    );
                });

            modelBuilder.Entity("Model.Models.Basket", b =>
                {
                    b.Property<Guid>("BasketId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.HasKey("BasketId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Basket");

                    b.HasData(
                        new { BasketId = new Guid("e3c578ed-3656-4acc-aa80-84a53a11e43b"), AccountId = new Guid("45e13b84-31ed-4920-922a-60f01841d311") }
                    );
                });

            modelBuilder.Entity("Model.Models.BasketItems", b =>
                {
                    b.Property<Guid>("IdBasketItems")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ArticleId");

                    b.Property<Guid>("BasketId");

                    b.Property<int>("Quantity");

                    b.Property<int>("UnitePrice");

                    b.HasKey("IdBasketItems");

                    b.HasIndex("ArticleId");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketItems");

                    b.HasData(
                        new { IdBasketItems = new Guid("4e9a415c-94d9-47d9-833c-526cdad97ef1"), ArticleId = new Guid("c170110d-1355-4060-9926-2028988d970c"), BasketId = new Guid("e3c578ed-3656-4acc-aa80-84a53a11e43b"), Quantity = 4, UnitePrice = 12 },
                        new { IdBasketItems = new Guid("71d30168-8889-4992-afe5-3f0eb314942a"), ArticleId = new Guid("c170110d-1355-4060-9926-2028988d970c"), BasketId = new Guid("e3c578ed-3656-4acc-aa80-84a53a11e43b"), Quantity = 8, UnitePrice = 190 },
                        new { IdBasketItems = new Guid("5f58b1ab-652b-4138-b7a8-3bcacdffa618"), ArticleId = new Guid("c170110d-1355-4060-9926-2028988d970c"), BasketId = new Guid("e3c578ed-3656-4acc-aa80-84a53a11e43b"), Quantity = 40, UnitePrice = 1200 }
                    );
                });

            modelBuilder.Entity("Model.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("InventoryItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArticleIdArticle");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Quantity");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("ArticleIdArticle");

                    b.ToTable("InventoryItem");
                });

            modelBuilder.Entity("Model.Models.InventorySystem", b =>
                {
                    b.Property<Guid>("InventorySysID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArticleIdArticle");

                    b.Property<DateTime>("DateInventory");

                    b.Property<int>("Quantity");

                    b.HasKey("InventorySysID");

                    b.HasIndex("ArticleIdArticle");

                    b.ToTable("InventorySystem");
                });

            modelBuilder.Entity("Model.Models.Login", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("LoginId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Logins");

                    b.HasData(
                        new { LoginId = new Guid("521c7fb8-5e09-430d-80c9-3556ce16b2c1"), CustomerId = new Guid("9d6a4941-2133-4fae-a148-e4a52880ee18"), Password = "admin", Username = "admin" },
                        new { LoginId = new Guid("8e746e71-a231-45c7-8c44-be3de0f9ade7"), CustomerId = new Guid("1fed12ee-bf69-4908-bd01-4a6b48fbf486"), Password = "admin", Username = "admin" }
                    );
                });

            modelBuilder.Entity("Model.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Model.Models.Customer", b =>
                {
                    b.HasBaseType("Model.Models.User");

                    b.Property<string>("Address");

                    b.Property<string>("Country");

                    b.Property<string>("Mail");

                    b.Property<int>("Status");

                    b.ToTable("Customer");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new { UserId = new Guid("9d6a4941-2133-4fae-a148-e4a52880ee18"), FirstName = "John", LastName = "Smith", Address = "2 Avenue NEW-YORK, USA", Country = "USA", Mail = "smith@john.com", Status = 1 },
                        new { UserId = new Guid("1fed12ee-bf69-4908-bd01-4a6b48fbf486"), FirstName = "John", LastName = "Smith", Address = "2 Avenue NEW-YORK, USA", Country = "USA", Mail = "smith@john.com", Status = 1 }
                    );
                });

            modelBuilder.Entity("Model.Models.Account", b =>
                {
                    b.HasOne("Model.Models.Customer", "Customer")
                        .WithOne("Account")
                        .HasForeignKey("Model.Models.Account", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Models.Basket", b =>
                {
                    b.HasOne("Model.Models.Account", "Account")
                        .WithOne("Basket")
                        .HasForeignKey("Model.Models.Basket", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Models.BasketItems", b =>
                {
                    b.HasOne("Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Model.Models.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Models.InventoryItem", b =>
                {
                    b.HasOne("Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleIdArticle");
                });

            modelBuilder.Entity("Model.Models.InventorySystem", b =>
                {
                    b.HasOne("Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleIdArticle");
                });

            modelBuilder.Entity("Model.Models.Login", b =>
                {
                    b.HasOne("Model.Models.Customer", "Customer")
                        .WithOne("Login")
                        .HasForeignKey("Model.Models.Login", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
