// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace Model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190124111108_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Models.Account", b =>
                {
                    b.Property<Guid>("IdAccount")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BillAddress");

                    b.Property<DateTime>("Closed");

                    b.Property<Guid>("CustomerId");

                    b.Property<bool>("IsClosed");

                    b.Property<DateTime>("Open");

                    b.HasKey("IdAccount");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new { IdAccount = new Guid("adf0a65c-5782-4795-b4e8-e5021c46c692"), BillAddress = "5 avenue new-york, usa", Closed = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), CustomerId = new Guid("ffd67da1-f694-4f81-b6e7-ac8d0c0b3018"), IsClosed = true, Open = new DateTime(2019, 1, 24, 0, 0, 0, 0, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("Model.Models.Article", b =>
                {
                    b.Property<Guid>("IdArticle")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activate");

                    b.Property<int>("DelievryTime");

                    b.Property<string>("Description");

                    b.Property<string>("Label");

                    b.Property<int>("PriceHT");

                    b.Property<int>("Tax");

                    b.HasKey("IdArticle");

                    b.ToTable("Articles");

                    b.HasData(
                        new { IdArticle = new Guid("78ace119-29bc-4903-a68f-fa10db32bcbf"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "Creme hydradanteXXL", PriceHT = 12, Tax = 3 },
                        new { IdArticle = new Guid("78ace119-29bc-4903-a68f-fa10db32bcaa"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "Creme hydradanteXXL", PriceHT = 12, Tax = 3 },
                        new { IdArticle = new Guid("78ace119-29bc-4903-a68f-fa10db32bcbb"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "pomade tonic", PriceHT = 12, Tax = 3 },
                        new { IdArticle = new Guid("4442f11b-de9d-4595-8970-41d4c84c6dfb"), Activate = true, DelievryTime = 3, Description = "Poterit ut Antiochensi dispelleret Antiochensi ut obsecranti principibus victu adesset.", Label = "Creme hydradanteXXL", PriceHT = 12, Tax = 3 }
                    );
                });

            modelBuilder.Entity("Model.Models.Basket", b =>
                {
                    b.Property<Guid>("BasketId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.HasKey("BasketId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Basket");

                    b.HasData(
                        new { BasketId = new Guid("0d5fb77d-506f-4827-ab26-40de925cba03"), AccountId = new Guid("adf0a65c-5782-4795-b4e8-e5021c46c692") },
                        new { BasketId = new Guid("d2523f87-552e-4a07-b1d4-e0bc8ac3da59"), AccountId = new Guid("add868fc-0392-4615-b311-b3db03b7cd9e") }
                    );
                });

            modelBuilder.Entity("Model.Models.BasketItems", b =>
                {
                    b.Property<Guid>("IdBasketItems")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ArticleId");

                    b.Property<Guid>("BasketId");

                    b.Property<int>("Quantity");

                    b.Property<int>("UnitePrice");

                    b.HasKey("IdBasketItems");

                    b.HasIndex("ArticleId");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketItems");

                    b.HasData(
                        new { IdBasketItems = new Guid("2c19e738-7c62-4489-9f45-e3df26b27a0a"), ArticleId = new Guid("4442f11b-de9d-4595-8970-41d4c84c6dfb"), BasketId = new Guid("d2523f87-552e-4a07-b1d4-e0bc8ac3da59"), Quantity = 4, UnitePrice = 12 },
                        new { IdBasketItems = new Guid("6447012f-a162-412e-9365-48d82a1178f0"), ArticleId = new Guid("4442f11b-de9d-4595-8970-41d4c84c6dfb"), BasketId = new Guid("d2523f87-552e-4a07-b1d4-e0bc8ac3da59"), Quantity = 8, UnitePrice = 190 },
                        new { IdBasketItems = new Guid("5a8768bf-15b9-4e13-afb5-392606e0dc49"), ArticleId = new Guid("4442f11b-de9d-4595-8970-41d4c84c6dfb"), BasketId = new Guid("d2523f87-552e-4a07-b1d4-e0bc8ac3da59"), Quantity = 40, UnitePrice = 1200 }
                    );
                });

            modelBuilder.Entity("Model.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("InventoryItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArticleIdArticle");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Quantity");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("ArticleIdArticle");

                    b.ToTable("InventoryItem");
                });

            modelBuilder.Entity("Model.Models.InventorySystem", b =>
                {
                    b.Property<Guid>("InventorySysID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArticleIdArticle");

                    b.Property<DateTime>("DateInventory");

                    b.Property<int>("Quantity");

                    b.HasKey("InventorySysID");

                    b.HasIndex("ArticleIdArticle");

                    b.ToTable("InventorySystem");
                });

            modelBuilder.Entity("Model.Models.Login", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("LoginId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Logins");

                    b.HasData(
                        new { LoginId = new Guid("8e612e28-a34f-4f28-88a6-7901635228b7"), CustomerId = new Guid("ffd67da1-f694-4f81-b6e7-ac8d0c0b3018"), Password = "admin", Username = "admin" }
                    );
                });

            modelBuilder.Entity("Model.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Model.Models.Customer", b =>
                {
                    b.HasBaseType("Model.Models.User");

                    b.Property<string>("Address");

                    b.Property<string>("Country");

                    b.Property<string>("Mail");

                    b.Property<int>("Status");

                    b.ToTable("Customer");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new { UserId = new Guid("ffd67da1-f694-4f81-b6e7-ac8d0c0b3018"), FirstName = "John", LastName = "Smith", Address = "2 Avenue NEW-YORK, USA", Country = "USA", Mail = "smith@john.com", Status = 1 }
                    );
                });

            modelBuilder.Entity("Model.Models.Account", b =>
                {
                    b.HasOne("Model.Models.Customer", "Customer")
                        .WithOne("Account")
                        .HasForeignKey("Model.Models.Account", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Models.Basket", b =>
                {
                    b.HasOne("Model.Models.Account", "Account")
                        .WithOne("Basket")
                        .HasForeignKey("Model.Models.Basket", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Models.BasketItems", b =>
                {
                    b.HasOne("Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Model.Models.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Models.InventoryItem", b =>
                {
                    b.HasOne("Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleIdArticle");
                });

            modelBuilder.Entity("Model.Models.InventorySystem", b =>
                {
                    b.HasOne("Model.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleIdArticle");
                });

            modelBuilder.Entity("Model.Models.Login", b =>
                {
                    b.HasOne("Model.Models.Customer", "Customer")
                        .WithOne("Login")
                        .HasForeignKey("Model.Models.Login", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
